server:
  port: 8080
spring:
  application:
    name: monolith-financial-system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    drop-first: true
    change-log: db/changelog/db.changelog-master.xml
    test-rollback-on-update: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}