version: '3.9'
services:

  postgres:
    container_name: ${APP_PREFIX}-postgres-db
    image: postgres:alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - postgres-storage:/var/lib/postgresql/data/

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ${APP_PREFIX}-app
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://${APP_PREFIX}-postgres-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres

volumes:
  postgres-storage:
    name: ${APP_PREFIX}-postgres-storage

