version: '3.9'
services:

  postgres:
    container_name: ${APP_PREFIX}-postgres-db
    image: postgres:alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - postgres-storage:/var/lib/postgresql/data/

volumes:
  postgres-storage:
    name: ${APP_PREFIX}-postgres-storage

